import Head from "next/head";
import { HeroText, HeroWrapper } from "../../components/styled/hero";

export default function Character() {
  return (
    <>
      <Head>
        <title>Character Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroWrapper>
        <HeroText>Character Name</HeroText>
      </HeroWrapper>
    </>
  );
}
