import Head from "next/head";
import * as Page from "../components/styled/page";
import { getAllLocations } from "../server/services/rick-and-morty-api";

function Home() {
  return (
    <>
      <Head>
        <title>Rick and Morty Locations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page.Header>Keeping Up with the Cronenbergs</Page.Header>
    </>
  );
}

export async function getServerSideProps() {
  const locations = await getAllLocations();

  return { props: { locations } };
}

export default Home;
