import Head from "next/head";
import Body from "../components/styled/body";
import { HeroText, HeroWrapper } from "../components/styled/hero";
import Page from "../components/styled/page";
import { getAllLocations } from "../server/services/rick-and-morty-api";

function Home() {
  return (
    <Page>
      <Head>
        <title>Rick and Morty Locations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroWrapper>
        <HeroText>Keeping Up with the Cronenbergs</HeroText>
      </HeroWrapper>
      <Body>some content</Body>
    </Page>
  );
}

export async function getServerSideProps() {
  const locations = await getAllLocations();

  return { props: { locations } };
}

export default Home;
