import Head from "next/head";
import * as Page from "../../components/styled/page";

export default function Location() {
  return (
    <>
      <Head>
        <title>Location Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page.Header>Location Name</Page.Header>
    </>
  );
}
